# Generated by Django 3.1 on 2020-12-11 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import network.accounts.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=10000)),
                ('html', models.TextField(default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, max_length=1024, upload_to=network.accounts.models.image_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (4, 'Spammer'), (2, 'Suspended'), (3, 'Banned')], db_index=True, default=0)),
                ('digest_prefs', models.IntegerField(choices=[(0, 'Never'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Email for every new thread (mailing list mode)')], default=2)),
                ('message_prefs', models.IntegerField(choices=[(3, 'Default'), (1, 'Email'), (0, 'Local Messages'), (2, 'No messages')], default=3)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=255)),
                ('max_upload_size', models.IntegerField(default=0)),
                ('role', models.IntegerField(choices=[(0, 'Reader'), (1, 'Moderator'), (2, 'Admin'), (3, 'Blog User')], default=0)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0)),
                ('alt_email_a', models.EmailField(blank=True, max_length=10000, null=True)),
                ('alt_email_b', models.EmailField(blank=True, max_length=10000, null=True)),
                ('degree', models.CharField(choices=[(None, 'Select your degree'), ('Undergraduate', 'Undergraduate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Doctor of Sciences', 'Doctor of Sciences')], max_length=30, null=True)),
                ('occupation', models.IntegerField(choices=[(0, 'Medical Doctor'), (1, 'Nurse'), (2, 'Dentist'), (3, 'Clinical Officer'), (4, 'Pharmacist'), (5, 'Laboratory Scientist')], default=0)),
                ('qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('expertise', models.CharField(blank=True, default='', max_length=10000)),
                ('affiliations', models.CharField(blank=True, default='', max_length=10000)),
                ('licence', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login', models.DateTimeField(db_index=True, max_length=255, null=True)),
                ('new_messages', models.IntegerField(db_index=True, default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('location', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('my_tags', models.CharField(blank=True, default='', max_length=10000)),
                ('watched_tags', models.CharField(blank=True, default='', max_length=10000)),
                ('text', models.TextField(blank=True, default='No bio available yet', max_length=10000, null=True)),
                ('html', models.TextField(blank=True, max_length=10000, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('med_verified', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=False)),
                ('opt_in', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, upload_to=network.accounts.models.get_avatar_full_path)),
                ('avatar_version', models.IntegerField(blank=True, default=0, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.IntegerField(choices=[(0, 'Spam'), (1, 'Not spam'), (2, 'Unknown')], default=2)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('subject', models.CharField(max_length=120)),
                ('unread', models.BooleanField(default=True)),
                ('sent_date', models.DateTimeField(db_index=True, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.messagebody')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'Preformed a moderation action.'), (1, 'Added verification data'), (2, 'Created an object.'), (3, 'Edited an object.'), (4, 'Logged in to the site.'), (5, 'Logged out of the site.'), (6, 'Browsing the site.')], default=6)),
                ('log_text', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
