# Generated by Django 3.1 on 2020-12-11 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
