# Generated by Django 3.1 on 2020-12-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201212_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_finished_registration',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
