# Generated by Django 3.1 on 2020-09-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, default='No bio available yet', max_length=10000, null=True),
        ),
    ]
