# Generated by Django 3.1 on 2020-09-21 08:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20200920_2230"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
