# Generated by Django 3.1 on 2020-11-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='med_verified',
            field=models.BooleanField(default=False),
        ),
    ]
