# Generated by Django 3.1 on 2020-09-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_profile_occupation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="scholar",
        ),
    ]
