# Generated by Django 3.1 on 2020-11-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_med_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
    ]
