# Generated by Django 3.1 on 2020-11-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userverification_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='action',
            field=models.IntegerField(choices=[(0, 'Preformed a moderation action.'), (1, 'Added verification data'), (2, 'Created an object.'), (3, 'Edited an object.'), (4, 'Logged in to the site.'), (5, 'Logged out of the site.'), (6, 'Browsing the site.')], default=6),
        ),
    ]
