# Generated by Django 3.1 on 2020-09-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_profile_scholar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
