# Generated by Django 3.1 on 2020-12-02 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import network.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_auto_20201130_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=network.accounts.models.get_avatar_full_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_version',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[(None, 'Select your degree'), ('Undergraduate', 'Undergraduate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Doctor of Sciences', 'Doctor of Sciences')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_email', models.BooleanField(default=False, verbose_name='I agree to receive transactional emails from 360Med Network registration system corresponding to actions related to me (e.g., submission status update, adding me as a moderator, information for review, etc.)')),
                ('info_email', models.BooleanField(default=False, verbose_name='I agree to receive informational emails related to 360Med Network relating to events, opportunities, etc.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
