# Generated by Django 3.1 on 2020-09-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
