# Generated by Django 3.1 on 2020-12-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201202_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
