# Generated by Django 3.1 on 2020-09-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliations',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
