# Generated by Django 3.1 on 2020-09-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_profile_affiliations"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="alt_email_a",
            field=models.EmailField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="alt_email_b",
            field=models.EmailField(blank=True, max_length=10000, null=True),
        ),
    ]
