# Generated by Django 3.0.7 on 2020-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0003_auto_20151126_1523"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="first_name",
            field=models.TextField(blank=True, null=True, verbose_name="First Name"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="last_name",
            field=models.TextField(blank=True, null=True, verbose_name="Last Name"),
        ),
    ]
