# Generated by Django 3.1 on 2020-10-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20200722_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Full Name'),
        ),
    ]
