# Generated by Django 3.1 on 2020-11-30 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('content', models.TextField(default='')),
                ('html', models.TextField(default='')),
                ('institution', models.CharField(db_index=True, default='', max_length=200)),
                ('apply_before', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('external_link', models.URLField(default='')),
                ('creation_date', models.DateTimeField(db_index=True)),
                ('uid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site')),
            ],
        ),
    ]
