# Generated by Django 3.1 on 2020-11-30 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20201130_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='event_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
