# Generated by Django 3.1 on 2020-12-01 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20201201_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lastedit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
