# Generated by Django 3.1 on 2020-11-30 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('forum', '0003_auto_20201130_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetup',
            new_name='Event',
        ),
    ]
