# Generated by Django 3.1 on 2020-12-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_event_lastedit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='site',
        ),
    ]
