# Generated by Django 3.1 on 2020-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='post_count',
        ),
        migrations.AddField(
            model_name='space',
            name='posts',
            field=models.ManyToManyField(related_name='space_posts', to='forum.Post'),
        ),
    ]
