# Generated by Django 3.1 on 2020-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20201127_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_val',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Spaces'),
        ),
    ]
