---
- hosts: all
  user: "{{ username | default(root) }}"

  tasks:

    - name: Reload supervisor
      become: yes
      service:
        name: supervisor
        state: restarted

    - name: Restart nginx
      become: yes
      service: name=nginx state=restarted
  
